# Generated by Django 4.2.2 on 2023-10-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0008_comment_likes"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="likes",),
    ]
