# Generated by Django 4.2.2 on 2023-10-26 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0010_comment_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_comment", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
