# Generated by Django 4.2.2 on 2023-11-23 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0015_post_is_editing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_editing",
        ),
    ]
