# Generated by Django 4.2.2 on 2023-11-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0016_remove_post_is_editing"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_editable",
            field=models.BooleanField(default=False),
        ),
    ]
